// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbbvmrwcwocovbetiofq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiYnZtcndjd29jb3ZiZXRpb2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzQ3NTEsImV4cCI6MjA2MTMxMDc1MX0.LoijQl8I8xyz5vEuILU1JDY3Kff-XaOIhdIq-qd2ezI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);